version: 2

elasticMq-image: &elasticMq-image
  image: softwaremill/elasticmq-native:latest
node: &node-image
  image: cimg/node:18.20.4

defaults: &defaults
  working_directory: ~/repo
  docker:
    - <<: *node-image

jobs:
  test:
    <<: *defaults
    docker:
      - <<: *node-image
      - <<: *elasticMq-image
    environment:
      ELASTIC_MQ_URL: http://localhost:9324
    steps:
      - checkout
      - run: yarn install
      - run: yarn lint
      - run: yarn test
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths: .

  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  test-publish:
    jobs:
      - test:
          context: LE
      - publish:
          context: LE
          requires:
            - test
          filters:
            branches:
              only: master
